#!/bin/bash

arg_num=$#

arg1=$1
arg2=$2

echo "Arg_number : $arg_num"

case $# in

0)
echo "Please enter one string to check the line number"
echo "Second argument will replace the first string to second"
echo "Pass argument as per your use-case" 
;;

1)
#grep -nir $arg1 monsoon1234 
 
sed -n '/'"$arg1"'/ =' monsoon1234

#'"$arg1"'- Considered as a string 
;;

2)
echo "Argument 1: $arg1"
echo "Argument 2: $arg2"
sed -e 's/'"$arg1"'/'"$arg2"'/g' monsoon1234
;;

3)
echo "More than two arguments are not allowed"
;;

*)
echo "Suggest few more functionality"
;;
esac
